# Generated by Django 5.2 on 2025-05-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_restaurant_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='picture',
            new_name='url',
        ),
    ]
